import matplotlib.pyplot as plt
import pandas as pd

def plot_popular_artists(no_features, counting_features, name_y = "", title = "", count = 10):
# Create a figure with 2 columns and 1 row
    fig, axs = plt.subplots(1, 2, figsize=(12, 6))  # Adjust figsize for better display
    fig.suptitle(title)
    
    #Artists and values, excluding features
    no_features = no_features.head(count).to_dict()
    artists_no_features = list(no_features.keys())
    values_no_features = list(no_features.values())
    
    # First bar plot
    axs[0].bar(artists_no_features, values_no_features, color='moccasin', edgecolor='black')
    axs[0].set_xlabel("Artist")
    axs[0].set_ylabel(name_y)
    axs[0].set_title("Top 15 Main Artists")
    axs[0].set_xticks(artists_no_features)
    axs[0].set_xticklabels(artists_no_features, rotation=45, ha='right')
    
    #Artists and values, counting features
    counting_features = counting_features.head(count).to_dict()
    artists_with_features = list(counting_features.keys())
    values_with_features = list(counting_features.values())

    # Second bar plot
    axs[1].bar(artists_with_features, values_with_features, color='limegreen', edgecolor='black')
    axs[1].set_xlabel("Artist")
    axs[1].set_ylabel(name_y)
    axs[1].set_title("Top 15 Artists Counting Features")
    axs[1].set_xticks(artists_with_features)
    axs[1].set_xticklabels(artists_with_features, rotation=45, ha='right')

    plt.tight_layout()
    plt.show()
    

def period_avg_position(data, genre, start_year, end_year, return_result = False):
    avg = data[(data.spotify_genre == genre) & (data.year >= start_year) & (data.year <= end_year)].peak_position.mean()
     
    if return_result:
        return avg
    
    print(f"Average position for {genre} songs during {start_year}-{end_year}: {round(avg, 2) * -1}")
    
    
def plot_genre_performance(data, genre, column = 'spotify_genre'):
    performance_over_years = data[data[column] == genre].year.value_counts().to_dict()
    performance_over_years = dict(sorted(performance_over_years.items()))
    
    plt.plot(performance_over_years.keys(), performance_over_years.values(), color = 'lightgreen', linewidth = 3)
    plt.scatter(performance_over_years.keys(), performance_over_years.values(), s = 15, color = 'indigo', zorder=5)
    plt.grid()
    plt.xlabel("Year")
    plt.ylabel("Number of songs")
    plt.title(f"{genre.capitalize()} songs over the years")
    
    

def spotify_feature_subplot(ax, data, col_name, clr = 'gold'):
    avg_values = data.groupby('spotify_genre')[col_name].mean().sort_values(ascending = False).head(5).to_dict()
    

    ax.bar(avg_values.keys(), avg_values.values(), color = clr)
    ax.set_xlabel("Top Genres")
    ax.set_ylabel("Average Value")
    ax.set_title(col_name.capitalize().replace("_", " "))
    
    x_labels = avg_values.keys()
    ax.set_xticks(list(x_labels))
    ax.set_xticklabels(x_labels, rotation=45, ha='right')
    if (data[col_name].sum() < 0):
        ax.invert_yaxis()
        
        
def boxplot_chart_performance(data, genre, start_year = 1958, end_year = 2024, interval = 1, column = 'spotify_genre'):
    filtered_years = data[(data[column] == genre) & (data.year >= start_year) & (data.year <= end_year)].copy()

    filtered_years['year_group'] = pd.cut(filtered_years['year'], bins = range(start_year, end_year + 1, interval), right = False)
    
    filtered_years.boxplot(column = "peak_position", by = "year_group", figsize = (8, 5))
    plt.ylabel('peak positions')
    plt.title("")
    plt.suptitle(f"Chart performance of {genre} songs over the years")
    plt.gca().invert_yaxis() #Invert the values, so that 1 is the highest position
    
    

genre_mapping = {
    "pop": "pop",
    "dance pop": "pop",
    "electropop": "pop",
    "pop rock": "pop",
    "indie pop": "pop",
    "brill building pop": "pop",
    "synthpop": "pop",
    "pop punk": "pop",
    "art pop": "pop",
    "teen pop": "pop",
    "bubblegum pop": "pop",
    "bedroom pop": "pop",
    "chamber pop": "pop",
    "country pop": "pop",
    "dream pop": "pop",
    "experimental pop": "pop",
    "folk-pop": "pop",
    "glam pop": "pop",
    "indie poptimism": "pop",
    "j-pop": "pop",
    "k-pop": "pop",
    "latin pop": "pop",
    "new romantic": "pop",
    "pop rap": "pop",
    "pop soul": "pop",
    "power pop": "pop",
    "soft pop": "pop",
    "sophisti-pop": "pop",
    "swedish pop": "pop",
    "tropical pop": "pop",
    "turkish pop": "pop",
    "euro pop": "pop",
    "baroque pop": "pop",
    "pop edm": "pop",
    "electronic pop": "pop",
    "britpop": "pop",
    "future pop": "pop",
    "hyperpop": "pop",
    "pop r&b": "pop",
    "pop reggaeton": "pop",
    "french pop": "pop",
    "italian pop": "pop",
    "opm": "pop",
    "v-pop": "pop",
    "mandopop": "pop",
    "c-pop": "pop",
    "cantopop": "pop",
        "rock": "rock",
    "alternative rock": "rock",
    "classic rock": "rock",
    "hard rock": "rock",
    "punk": "rock",
    "grunge": "rock",
    "garage rock": "rock",
    "indie rock": "rock",
    "metal": "rock",
    "post-rock": "rock",
    "rock-and-roll": "rock",
    "emo": "rock",
    "progressive rock": "rock",
    "psychedelic rock": "rock",
    "arena rock": "rock",
    "blues rock": "rock",
    "folk rock": "rock",
    "glam rock": "rock",
    "gothic rock": "rock",
    "industrial rock": "rock",
    "math rock": "rock",
    "new wave": "rock",
    "nu metal": "rock",
    "pop rock": "rock",
    "punk rock": "rock",
    "shoegaze": "rock",
    "southern rock": "rock",
    "space rock": "rock",
    "stoner rock": "rock",
    "surf rock": "rock",
    "noise rock": "rock",
    "art rock": "rock",
    "british rock": "rock",
    "j-rock": "rock",
    "post-punk": "rock",
        "hip hop": "hip hop",
    "rap": "hip hop",
    "trap": "hip hop",
    "gangsta rap": "hip hop",
    "underground hip hop": "hip hop",
    "conscious hip hop": "hip hop",
    "crunk": "hip hop",
    "freestyle": "hip hop",
    "boom bap": "hip hop",
    "dirty south": "hip hop",
    "east coast hip hop": "hip hop",
    "west coast hip hop": "hip hop",
    "alternative hip hop": "hip hop",
    "southern hip hop": "hip hop",
    "g-funk": "hip hop",
    "chicano rap": "hip hop",
    "drill": "hip hop",
    "grime": "hip hop",
    "mumble rap": "hip hop",
    "trap soul": "hip hop",
    "hyphy": "hip hop",
    "uk drill": "hip hop",
    "emo rap": "hip hop",
    "jazz rap": "hip hop",
    "latin hip hop": "hip hop",
    "christian hip hop": "hip hop",
    "trap latino": "hip hop",
    "phonk": "hip hop",
    "cloud rap": "hip hop",
    "melodic rap": "hip hop",
    "hardcore hip hop": "hip hop",
    "rap metal": "hip hop",
    "rap rock": "hip hop",
    "old school hip hop": "hip hop",
    "miami bass": "hip hop",
    "bounce": "hip hop",
    "rap français": "hip hop",
    "french hip hop": "hip hop",
    "rap espanol": "hip hop",
    "latino trap": "hip hop",
    "hip hop soul": "hip hop",
    "conscious rap": "hip hop",
    "drill beats": "hip hop",
    "brooklyn drill": "hip hop",
    "trap music": "hip hop",
    "k-rap": "hip hop",
    "uk grime": "hip hop",
    "trap brasil": "hip hop",
    "electronic": "electronic",
    "edm": "electronic",
    "house": "electronic",
    "techno": "electronic",
    "trance": "electronic",
    "dubstep": "electronic",
    "drum and bass": "electronic",
    "electro": "electronic",
    "ambient": "electronic",
    "glitch hop": "electronic",
    "deep house": "electronic",
    "future bass": "electronic",
    "synthwave": "electronic",
    "chillwave": "electronic",
    "downtempo": "electronic",
    "hardcore techno": "electronic",
    "industrial": "electronic",
    "progressive house": "electronic",
    "tech house": "electronic",
    "tropical house": "electronic",
    "big room": "electronic",
    "chiptune": "electronic",
    "breakbeat": "electronic",
    "electro house": "electronic",
    "electro swing": "electronic",
    "future house": "electronic",
    "hardstyle": "electronic",
    "idm": "electronic",
    "moombahton": "electronic",
    "bass house": "electronic",
    "glitch": "electronic",
    "microhouse": "electronic",
    "neurofunk": "electronic",
    "progressive trance": "electronic",
    "psybient": "electronic",
    "psytrance": "electronic",
    "uk garage": "electronic",
    "vaporwave": "electronic",
    "electronic trap": "electronic",
    "electronic pop": "electronic",
    "electronic rock": "electronic",
    "electronic dance": "electronic",
    "drumstep": "electronic",
    "electronica": "electronic",
    "future garage": "electronic",
        "jazz": "jazz",
    "smooth jazz": "jazz",
    "bebop": "jazz",
    "cool jazz": "jazz",
    "free jazz": "jazz",
    "fusion": "jazz",
    "hard bop": "jazz",
    "latin jazz": "jazz",
    "swing": "jazz",
    "vocal jazz": "jazz",
    "acid jazz": "jazz",
    "avant-garde jazz": "jazz",
    "big band": "jazz",
    "contemporary jazz": "jazz",
    "gypsy jazz": "jazz",
    "jazz fusion": "jazz",
    "jazz rap": "jazz",
    "nu jazz": "jazz",
    "soul jazz": "jazz",
    "trad jazz": "jazz",
    "jazz blues": "jazz",
    "jazz funk": "jazz",
    "jazz swing": "jazz",
    "jazz quartet": "jazz",
    "post-bop": "jazz",
    "ragtime": "jazz",
    "jazz pop": "jazz",
    "jazz rock": "jazz",
    "jazz ballad": "jazz",
    "jazz guitar": "jazz",
    "smooth jazz fusion": "jazz",
    "conscious jazz": "jazz",
    "country": "country",
    "alt-country": "country",
    "bluegrass": "country",
    "honky tonk": "country",
    "outlaw country": "country",
    "traditional country": "country",
    "country rock": "country",
    "contemporary country": "country",
    "americana": "country",
    "country pop": "country",
    "nashville sound": "country",
    "red dirt": "country",
    "modern country": "country",
    "country blues": "country",
    "country gospel": "country",
    "texas country": "country",
    "western swing": "country",
    "new traditional country": "country",
    "country soul": "country",
    "hillbilly": "country",
    "country-folk": "country",
    "progressive country": "country",
    "country rap": "country",
    "country jazz": "country",
    "country metal": "country",
    "country rockabilly": "country",
    "alt-country rock": "country",
    "country blues rock": "country",
    "country indie": "country",
    "cowboy": "country",
    "reggae": "reggae",
    "dancehall": "reggae",
    "roots reggae": "reggae",
    "dub": "reggae",
    "ska": "reggae",
    "rocksteady": "reggae",
    "reggaeton": "reggae",
    "lovers rock": "reggae",
    "reggae fusion": "reggae",
    "dubstep": "reggae",
    "dub reggae": "reggae",
    "rasta": "reggae",
    "Jamaican reggae": "reggae",
    "reggae pop": "reggae",
    "reggae blues": "reggae",
    "reggae jazz": "reggae",
    "digital dancehall": "reggae",
    "roots dub": "reggae",
    "reggae soul": "reggae",
    "reggae rock": "reggae",
    "reggae trance": "reggae",
    "latin": "latin",
    "salsa": "latin",
    "bachata": "latin",
    "reggaeton": "latin",
    "merengue": "latin",
    "cumbia": "latin",
    "bossa nova": "latin",
    "samba": "latin",
    "tango": "latin",
    "mariachi": "latin",
    "ranchera": "latin",
    "norteno": "latin",
    "corridos": "latin",
    "latin pop": "latin",
    "latin rock": "latin",
    "latin jazz": "latin",
    "afro-latin": "latin",
    "tropicalia": "latin",
    "charanga": "latin",
    "latin trap": "latin",
    "bolero": "latin",
    "salsa dura": "latin",
    "reggaeton trap": "latin",
    "latin dance": "latin",
    "latin electronic": "latin",
    "pop latino": "latin",
    "chicha": "latin",
    "tropical pop": "latin",
    "blues": "blues",
    "delta blues": "blues",
    "chicago blues": "blues",
    "electric blues": "blues",
    "acoustic blues": "blues",
    "country blues": "blues",
    "urban blues": "blues",
    "blues rock": "blues",
    "traditional blues": "blues",
    "modern blues": "blues",
    "soul blues": "blues",
    "boogie woogie": "blues",
    "swamp blues": "blues",
    "jump blues": "blues",
    "piano blues": "blues",
    "rhythm and blues": "blues",
    "juke joint blues": "blues",
    "electric delta blues": "blues",
    "british blues": "blues",
    "gospel blues": "blues",
    "texas blues": "blues",
    "west coast blues": "blues",
    "roots blues": "blues",
    "metal": "metal",
    "heavy metal": "metal",
    "thrash metal": "metal",
    "death metal": "metal",
    "black metal": "metal",
    "doom metal": "metal",
    "power metal": "metal",
    "progressive metal": "metal",
    "symphonic metal": "metal",
    "gothic metal": "metal",
    "metalcore": "metal",
    "grindcore": "metal",
    "industrial metal": "metal",
    "sludge metal": "metal",
    "speed metal": "metal",
    "stoner metal": "metal",
    "post-metal": "metal",
    "nu metal": "metal",
    "folk metal": "metal",
    "traditional metal": "metal",
    "heavy psych": "metal",
    "deathcore": "metal",
    "melodic death metal": "metal",
    "brutal death metal": "metal",
    "folk": "folk",
    "traditional folk": "folk",
    "folk rock": "folk",
    "indie folk": "folk",
    "americana": "folk",
    "contemporary folk": "folk",
    "neo-folk": "folk",
    "folk metal": "folk",
    "singer-songwriter": "folk",
    "celtic folk": "folk",
    "appalachian folk": "folk",
    "british folk": "folk",
    "folk punk": "folk",
    "folk blues": "folk",
    "world folk": "folk",
    "modern folk": "folk",
    "classic folk": "folk",
    "psych folk": "folk",
    "roots folk": "folk",
    "country folk": "folk",
    "canadian folk": "folk",
    "old-time": "folk",
    "scottish folk": "folk",
    "irish folk": "folk",
    "folk revival": "folk",
    "soul": "soul",
    "classic soul": "soul",
    "motown": "soul",
    "neo-soul": "soul",
    "southern soul": "soul",
    "psychedelic soul": "soul",
    "smooth soul": "soul",
    "funk soul": "soul",
    "soul jazz": "soul",
    "deep soul": "soul",
    "urban soul": "soul",
    "contemporary soul": "soul",
    "traditional soul": "soul",
    "modern soul": "soul",
    "northern soul": "soul",
    "gospel soul": "soul",
    "blues soul": "soul",
    "soul pop": "soul",
    "soul funk": "soul",
    "soulful house": "soul",
    "disco": "disco",
    "classic disco": "disco",
    "euro disco": "disco",
    "hi-nrg": "disco",
    "italo disco": "disco",
    "disco house": "disco",
    "funky disco": "disco",
    "disco pop": "disco",
    "disco soul": "disco",
    "disco fever": "disco",
    "disco revival": "disco",
    "disco funk": "disco",
    "disco edm": "disco",
    "disco rock": "disco",
    "space disco": "disco",
    "dance disco": "disco",
    "disco remix": "disco",
    "disco classics": "disco",
    "jazz": "jazz",
    "smooth jazz": "jazz",
    "bebop": "jazz",
    "cool jazz": "jazz",
    "free jazz": "jazz",
    "fusion": "jazz",
    "hard bop": "jazz",
    "latin jazz": "jazz",
    "swing": "jazz",
    "vocal jazz": "jazz",
    "acid jazz": "jazz",
    "avant-garde jazz": "jazz",
    "big band": "jazz",
    "contemporary jazz": "jazz",
    "gypsy jazz": "jazz",
    "jazz fusion": "jazz",
    "jazz rap": "jazz",
    "nu jazz": "jazz",
    "soul jazz": "jazz",
    "trad jazz": "jazz",
    "jazz blues": "jazz",
    "jazz funk": "jazz",
    "jazz swing": "jazz",
    "jazz quartet": "jazz",
    "post-bop": "jazz",
    "ragtime": "jazz",
    "jazz pop": "jazz",
    "jazz rock": "jazz",
    "jazz ballad": "jazz",
    "jazz guitar": "jazz",
    "smooth jazz fusion": "jazz",
    "conscious jazz": "jazz",
}